name: Build TWRP Recovery Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAKEFLAGS: "-j$(nproc)"  # Use all available cores for faster building

    steps:
      # Checkout the code from your repository
      - name: Checkout device tree
        uses: actions/checkout@v3
        with:
          repository: twrpdtgen/android_device_motorola_cancunf
          path: device/motorola/cancunf

      # Set up the TWRP repo
      - name: Init TWRP repo
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex \
              git gnupg gperf libncurses5-dev libssl-dev \
              python3 python-is-python3 repo rsync unzip \
              zip zlib1g-dev

          # Initialize the TWRP repo
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1
          repo sync --force-sync --no-tags --no-clone-bundle -j$(nproc)

      # Clone the device tree for your device
      - name: Set up device tree for motorola_cancunf
        run: |
          mkdir -p device/motorola/cancunf
          git clone https://github.com/twrpdtgen/android_device_motorola_cancunf.git device/motorola/cancunf

      # Build TWRP Recovery Image
      - name: Build TWRP
        run: |
          source build/envsetup.sh
          lunch omni_cancunf-eng
          mka recoveryimage

      # Upload the recovery image artifact
      - name: Upload TWRP Recovery Image
        uses: actions/upload-artifact@v3
        with:
          name: twrp-recovery-img
          path: out/target/product/cancunf/recovery.img
